### PR TITLE
nginx-upload-module: add openssl lib dependency

### PR DESCRIPTION
**Pull request by matthew-l-weber**
When building against 1.11.2+, requires additional
-lcrypto dependency. (Nginx changed crypto approach
and dependencies for openssl are no longer default)

More details found here:
https://github.com/vkholodkov/nginx-upload-module/issues/79

Resolves:
objs/addon/nginx-upload-70bee48f1811eecd255ed094ce9f0fb560c390c3/ngx_http_upload_module.o \
objs/ngx_modules.o \
-ldl -lpthread -lpthread -lpcre -lz -latomic_ops \
-Wl,-E
ngx_http_upload_module.o: In function `ngx_http_upload_flush_output_buffer':
ngx_http_upload_module.c:1625: undefined reference to `MD5_Update'
ngx_http_upload_module.c:1628: undefined reference to `SHA1_Update'
ngx_http_upload_module.c:1631: undefined reference to `SHA256_Update'
ngx_http_upload_module.c:1634: undefined reference to `SHA512_Update'

Signed-off-by: Matthew Weber <matthew.l.weber@gmail.com>

### CODE REVIEW

**Comment by grunjol** [comment]
I confirm this fix the build with 1.13.3

**Comment by Austinb** [comment]
See #88 and use the 2.255 branch and see if that solves your issue.

**Comment by khavishbhundoo** [comment]
@fdintino This pull request can be safely closed
