### ISSUE TITLE
module don't build with nginx 1.8.0

### ISSUE THREAD

**Issue by mailo84** [fdintino/nginx-upload-module#72]
/root/rpmbuild/BUILD/nginx-1.8.0/nginx_upload_module-2.2.0/ngx_http_upload_module.c:245: error: static declaration of 'ngx_http_request_body_save_filter' follows non-static declaration
src/http/ngx_http_core_module.h:542: note: previous declaration of 'ngx_http_request_body_save_filter' was here
make[1]: **\* [objs/addon/nginx_upload_module-2.2.0/ngx_http_upload_module.o] Error 1

**Comment by helal00** [comment]
same issue here

**Comment by helal00** [comment]
never mind...just need to clone the 2.2 branch as it contains newer commits.
git clone -b 2.2 https://github.com/vkholodkov/nginx-upload-module

**Comment by MichealSang** [comment]
thanks helal00...
it work for me...

**Comment by Nmishin** [comment]
same issue:
		../nginx_upload_module-2.2.0/ngx_http_upload_module.c
../nginx_upload_module-2.2.0/ngx_http_upload_module.c: In function 'ngx_http_read_upload_client_request_body':
../nginx_upload_module-2.2.0/ngx_http_upload_module.c:2628: error: 'ngx_http_request_body_t' has no member named 'to_write'
../nginx_upload_module-2.2.0/ngx_http_upload_module.c:2687: error: 'ngx_http_request_body_t' has no member named 'to_write'
../nginx_upload_module-2.2.0/ngx_http_upload_module.c: In function 'ngx_http_do_read_upload_client_request_body':
../nginx_upload_module-2.2.0/ngx_http_upload_module.c:2769: error: 'ngx_http_request_body_t' has no member named 'to_write'
../nginx_upload_module-2.2.0/ngx_http_upload_module.c:2785: error: 'ngx_http_request_body_t' has no member named 'to_write'
../nginx_upload_module-2.2.0/ngx_http_upload_module.c:2877: error: 'ngx_http_request_body_t' has no member named 'to_write'
make[1]: *** [objs/addon/nginx_upload_module-2.2.0/ngx_http_upload_module.o] Error 1
make[1]: Leaving directory `/usr/build/nginx-1.8.0'
make: *** [build] Error 2

nginx-1.8.0

**Comment by remyd1** [comment]
Thanks helal00.

Why not putting branch 2.2 as the default one ? It works with this version.

Ubuntu 15.04, nginx 1.8.1.

My install steps just for information:
```
wget http://nginx.org/download/nginx-1.8.1.tar.gz
tar xvf nginx-1.8.1.tar.gz
wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.38.tar.bz2
tar -xjf pcre-8.38.tar.bz2
git clone -b 2.2 https://github.com/vkholodkov/nginx-upload-module
cd nginx-1.8.1/
./configure --prefix=/opt/nginx --with-http_ssl_module --add-module=../nginx-upload-module --with-pcre=../pcre-8.38/
sudo make
sudo make install
```

**Comment by NobleGestures** [comment]
This works! Thanks much helal00

**Comment by wanggaolin** [comment]
i useage  git clone -b 2.2 https://github.com/vkholodkov/nginx-upload-module ,it's ok
but, in my nignx config: upload_limit_rate 128k; it's useless　
@helal00

**Comment by khavishbhundoo** [comment]
@fdintino  You can close this issue
