### ISSUE TITLE
can't compile on nginx-0.8.52

### ISSUE THREAD

**Issue by kalloc** [fdintino/nginx-upload-module#4]
<pre>
gcc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Wunused-function -Wunused-variable -Wunused-value -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I src/http/modules/perl -I ./nginx-upload-module -I src/mail \
        -o objs/addon/nginx-upload-module/ngx_http_upload_module.o \
        ./nginx-upload-module/ngx_http_upload_module.c
./nginx-upload-module/ngx_http_upload_module.c: In function ‘ngx_http_upload_merge_loc_conf’:
./nginx-upload-module/ngx_http_upload_module.c:1104: error: ‘ngx_garbage_collector_temp_handler’ undeclared (first use in this function)
./nginx-upload-module/ngx_http_upload_module.c:1104: error: (Each undeclared identifier is reported only once
./nginx-upload-module/ngx_http_upload_module.c:1104: error: for each function it appears in.)
cc1: warnings being treated as errors
./nginx-upload-module/ngx_http_upload_module.c:1104: error: passing argument 1 of ‘ngx_conf_merge_path_value’ from incompatible pointer type
src/core/ngx_file.h:140: note: expected ‘struct ngx_conf_t *’ but argument is of type ‘struct ngx_path_t *’
./nginx-upload-module/ngx_http_upload_module.c:1104: error: passing argument 2 of ‘ngx_conf_merge_path_value’ from incompatible pointer type
src/core/ngx_file.h:140: note: expected ‘struct ngx_path_t **’ but argument is of type ‘struct ngx_path_t *’
./nginx-upload-module/ngx_http_upload_module.c:1104: error: passing argument 3 of ‘ngx_conf_merge_path_value’ from incompatible pointer type
src/core/ngx_file.h:140: note: expected ‘struct ngx_path_t *’ but argument is of type ‘char *’
./nginx-upload-module/ngx_http_upload_module.c:1104: error: passing argument 4 of ‘ngx_conf_merge_path_value’ makes pointer from integer without a cast
src/core/ngx_file.h:140: note: expected ‘struct ngx_path_init_t *’ but argument is of type ‘int’
./nginx-upload-module/ngx_http_upload_module.c:1104: error: too many arguments to function ‘ngx_conf_merge_path_value’
./nginx-upload-module/ngx_http_upload_module.c: In function ‘ngx_http_upload_pass_form_field’:
./nginx-upload-module/ngx_http_upload_module.c:1490: error: passing argument 1 of ‘ngx_regex_compile’ from incompatible pointer type
src/core/ngx_regex.h:45: note: expected ‘struct ngx_regex_compile_t *’ but argument is of type ‘struct ngx_str_t *’
./nginx-upload-module/ngx_http_upload_module.c:1490: error: too many arguments to function ‘ngx_regex_compile’
./nginx-upload-module/ngx_http_upload_module.c:1490: error: assignment makes pointer from integer without a cast
./nginx-upload-module/ngx_http_upload_module.c:1497: error: implicit declaration of function ‘ngx_regex_capture_count’
./nginx-upload-module/ngx_http_upload_module.c:1501: error: ‘ngx_regex_capture_count_n’ undeclared (first use in this function)
./nginx-upload-module/ngx_http_upload_module.c:1501: error: expected ‘)’ before string constant
make[1]: *** [objs/addon/nginx-upload-module/ngx_http_upload_module.o] Error 1
make[1]: Leaving directory `/root/dist/nginx-0.8.52'
</pre>
