### ISSUE TITLE
compiled error

### ISSUE THREAD

**Issue by ghost** [fdintino/nginx-upload-module#61]
cc -c   -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I /Users/batuhangoksu/Desktop/nginx-upload-module-master -I src/mail \
        -o objs/addon/nginx-upload-module-master/ngx_http_upload_module.o \
        /Users/batuhangoksu/Desktop/nginx-upload-module-master/ngx_http_upload_module.c
/Users/batuhangoksu/Desktop/nginx-upload-module-master/ngx_http_upload_module.c:706:9: warning: 
      'MD5_Init' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
        MD5Init(&u->md5_ctx->md5);
        ^
/Users/batuhangoksu/Desktop/nginx-upload-module-master/ngx_http_upload.h:15:21: note: expanded from
      macro 'MD5Init'
# define  MD5Init    MD5_Init

```
                ^
```

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/openssl/md5.h:113:5: note: 
      'MD5_Init' declared here
int MD5_Init(MD5_CTX *c) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
    ^
/Users/batuhangoksu/Desktop/nginx-upload-module-master/ngx_http_upload_module.c:709:9: warning: 
      'SHA1_Init' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
        SHA1_Init(&u->sha1_ctx->sha1);
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/openssl/sha.h:121:5: note: 
      'SHA1_Init' declared here
int SHA1_Init(SHA_CTX *c) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
    ^
/Users/batuhangoksu/Desktop/nginx-upload-module-master/ngx_http_upload_module.c:750:13: warning: 
      'MD5_Final' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
            MD5Final(u->md5_ctx->md5_digest, &u->md5_ctx->md5);
            ^
/Users/batuhangoksu/Desktop/nginx-upload-module-master/ngx_http_upload.h:17:21: note: expanded from
      macro 'MD5Final'
# define  MD5Final   MD5_Final

```
                ^
```

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/openssl/md5.h:115:5: note: 
      'MD5_Final' declared here
int MD5_Final(unsigned char *md, MD5_CTX *c) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
    ^
/Users/batuhangoksu/Desktop/nginx-upload-module-master/ngx_http_upload_module.c:753:13: warning: 
      'SHA1_Final' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
            SHA1_Final(u->sha1_ctx->sha1_digest, &u->sha1_ctx->sha1);
            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/openssl/sha.h:123:5: note: 
      'SHA1_Final' declared here
int SHA1_Final(unsigned char *md, SHA_CTX *c) DEPRECATED_IN_MAC_OS_X_VERSION_10_7_AND_LATER;
    ^
/Users/batuhangoksu/Desktop/nginx-upload-module-master/ngx_http_upload_module.c:850:13: warning: 
      'MD5_Update' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
            MD5Update(&u->md5_ctx->md5, cl->buf->pos, cl->buf->last - cl->buf->pos);
            ^
/Users/batuhangoksu/Desktop/nginx-upload-module-master/ngx_http_upload.h:16:21: note: expanded from
      macro 'MD5Update'
# define  MD5Update  MD5_Update

```
                ^
```

/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/openssl/md5.h:114:5: note: 
      'MD5_Update' declared here
int MD5_Update(MD5_CTX _c, const void *data, size_t len) DEPRECATED_IN_MAC_OS_X_VERSION_10_7...
    ^
/Users/batuhangoksu/Desktop/nginx-upload-module-master/ngx_http_upload_module.c:853:13: warning: 
      'SHA1_Update' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]
            SHA1_Update(&u->sha1_ctx->sha1, cl->buf->pos, cl->buf->last - cl->buf->pos);
            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/openssl/sha.h:122:5: note: 
      'SHA1_Update' declared here
int SHA1_Update(SHA_CTX *c, const void *data, size_t len) DEPRECATED_IN_MAC_OS_X_VERSION_10_...
    ^
/Users/batuhangoksu/Desktop/nginx-upload-module-master/ngx_http_upload_module.c:1104:31: error: use
      of undeclared identifier 'ngx_garbage_collector_temp_handler'
                              ngx_garbage_collector_temp_handler, cf);
                              ^
/Users/batuhangoksu/Desktop/nginx-upload-module-master/ngx_http_upload_module.c:1922:9: error: no
      member named 'to_write' in 'ngx_http_request_body_t'
    rb->to_write = rb->bufs;
    ~~  ^
/Users/batuhangoksu/Desktop/nginx-upload-module-master/ngx_http_upload_module.c:1991:58: error: no
      member named 'to_write' in 'ngx_http_request_body_t'
                    ngx_http_process_request_body(r, rb->to_write));
                                                     ~~  ^
/Users/batuhangoksu/Desktop/nginx-upload-module-master/ngx_http_upload_module.c:1997:21: error: no
      member named 'to_write' in 'ngx_http_request_body_t'
                rb->to_write = rb->bufs->next ? rb->bufs->next : rb->bufs;
                ~~  ^
/Users/batuhangoksu/Desktop/nginx-upload-module-master/ngx_http_upload_module.c:2063:46: error: no
      member named 'to_write' in 'ngx_http_request_body_t'
        ngx_http_process_request_body(r, rb->to_write));
                                         ~~  ^
6 warnings and 5 errors generated.
make[1]: *_\* [objs/addon/nginx-upload-module-master/ngx_http_upload_module.o] Error 1
make: **\* [build] Error 2

**Comment by jslhcl** [comment]
@lcharkiewicz , same error happens in nginx 1.9.5 and nginx_upload_module 2.2.0: 
md5.h: no such file or directory
I've already installed libssl-dev and there is openssl/md5.h in my machine
but looks that the macro NGX_HAVE_OPENSSL_MD5_H is not enabled.
environment: Ubuntu 14.04

**Comment by jslhcl** [comment]
Oh, I will say, nginx_upload_module 2.2.0 cannot work with nginx 1.9.5:
./src/nginx_upload_module-2.2.0/ngx_http_upload_module.c: In function ‘ngx_http_read_upload_client_request_body’:
./src/nginx_upload_module-2.2.0/ngx_http_upload_module.c:2628:15: error: ‘ngx_http_request_body_t’ has no member named ‘to_write’
             rb->to_write = rb->bufs;
               ^

@vkholodkov

**Comment by jfwblog** [comment]
I am seconding @jslhcl report that branch 2.2 fails to compile on nginx 1.11.4

I worked around the problem by adding 
```
#define NGX_HAVE_OPENSSL_MD5_H 1
#define NGX_OPENSSL_MD5 1
#define NGX_HAVE_OPENSSL_SHA1_H 1
```

on line 11 of `ngx_http_upload_module.c`

This is only a HACK FIX that will only work if you know you have openssl libraries installed.  If you do not have openssl installed this will make your build even less correct.

Long-term solution would be nice.

**Comment by khavishbhundoo** [comment]
@fdintino This issue can be closed as its irrelevant to the latest version
