### ISSUE TITLE
Is project dead ?

### ISSUE THREAD

**Issue by antonakv** [fdintino/nginx-upload-module#95]
Hello,

There are no even bug fix releases from 2008 year.
Is project dead ?

Best regards,
Anton

**Comment by vkholodkov** [comment]
Well, if I was to apply a state of mind to this project, then I'd rather say it's on holidays :D 

Do you have a specific issue to discuss?

**Comment by antonakv** [comment]
Hehe :-) I see.
Yep, there is md5.h related compilation error. Widely discussed on stackoverflow.com, so on.

```
	-o objs/addon/nginx-upload-module/ngx_upload_discard_filter_module.o \
	/usr/src/nginx-upload-module/ngx_upload_discard_filter_module.c
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /usr/src/openssl-1.1.0f/.openssl/include -I /usr/include/libxml2 -I objs \
	-o objs/ngx_modules.o \
	objs/ngx_modules.c
In file included from /usr/src/nginx-upload-module/ngx_http_upload_module.c:10:0:
/usr/src/nginx-upload-module/ngx_http_upload.h:11:17: fatal error: md5.h: No such file or directory
 #include <md5.h>
                 ^
compilation terminated.
In file included from /usr/src/nginx-upload-module/ngx_upload_unzip_filter_module.c:10:0:
/usr/src/nginx-upload-module/ngx_http_upload.h:11:17: fatal error: md5.h: No such file or directory
 #include <md5.h>
                 ^
compilation terminated.
objs/Makefile:1773: recipe for target 'objs/addon/nginx-upload-module/ngx_upload_unzip_filter_module.o' failed
make[1]: *** [objs/addon/nginx-upload-module/ngx_upload_unzip_filter_module.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [objs/addon/nginx-upload-module/ngx_http_upload_module.o] Error 1
objs/Makefile:1766: recipe for target 'objs/addon/nginx-upload-module/ngx_http_upload_module.o' failed
In file included from /usr/src/nginx-upload-module/ngx_upload_discard_filter_module.c:8:0:
/usr/src/nginx-upload-module/ngx_http_upload.h:11:17: fatal error: md5.h: No such file or directory
 #include <md5.h>
                 ^
compilation terminated.
make[1]: *** [objs/addon/nginx-upload-module/ngx_upload_discard_filter_module.o] Error 1
objs/Makefile:1780: recipe for target 'objs/addon/nginx-upload-module/ngx_upload_discard_filter_module.o' failed
make[1]: Leaving directory '/usr/src/nginx-1.12.1'
make: *** [build] Error 2
Makefile:8: recipe for target 'build' failed
```

And this change recommended on forums doesn't help anymore:
```
sed -i '11 a #define NGX_HAVE_OPENSSL_MD5_H 1\n#define NGX_OPENSSL_MD5 1\n#define NGX_HAVE_OPENSSL_SHA1_H 1\n' /usr/src/nginx-upload-module/ngx_http_upload_module.c
```

Could you please help ?

Thanks.

**Comment by vkholodkov** [comment]
I can't assign anyone to this project now -- too busy with my startup.

This issue is very simple, try to fix it yourself. Best solution would be to disable MD5 at all. If you need it though, make sure MD5 library headers are available and included by the module.

**Comment by antonakv** [comment]
Ok! Thanks.

**Comment by antonakv** [comment]
I added full path to md5.h and sha.h in source code. Result:
/usr/src/nginx-upload-module/ngx_http_upload_module.c: In function 'ngx_http_upload_start_handler':
/usr/src/nginx-upload-module/ngx_http_upload_module.c:710:9: error: implicit declaration of function 'MD5Init' [-Werror=implicit-function-declaration]
         MD5Init(&u->md5_ctx->md5);
         ^~~~~~~
/usr/src/nginx-upload-module/ngx_http_upload_module.c: In function 'ngx_http_upload_finish_handler':
/usr/src/nginx-upload-module/ngx_http_upload_module.c:754:13: error: implicit declaration of function 'MD5Final' [-Werror=implicit-function-declaration]
             MD5Final(u->md5_ctx->md5_digest, &u->md5_ctx->md5);
             ^~~~~~~~
MD5Init is depricated and was removed from OpenSSL.

**Comment by syedwaseemjan** [comment]
Hey @antonakv , were you able to resolve this issue? I am facing the same issue.

**Comment by amichaelgrant** [comment]
It turns out modifying ngx_http_upload_module.c might help resolve the problem.
Introduce the lines below:
```
#include <openssl/md5.h>
#define  MD5Init    MD5_Init
#define  MD5Update  MD5_Update
#define  MD5Final   MD5_Final
#include <openssl/sha.h>
```
Then comment out these lines located at the top:
```
// #if (NGX_HAVE_OPENSSL_MD5_H)
// #include <openssl/md5.h>
// #else
// #include <md5.h>
// #endif

// #if (NGX_OPENSSL_MD5)
// #define  MD5Init    MD5_Init
// #define  MD5Update  MD5_Update
// #define  MD5Final   MD5_Final
// #endif

// #if (NGX_HAVE_OPENSSL_SHA1_H)
// #include <openssl/sha.h>
// #else
// #include <sha.h>
// #endif
```

Let me point out that I am working with nginx 1.12 and the latest version of nginx-upload-module

**Comment by davama** [comment]
@amichaelgrant thank you for posting

I added the `openssl/md5.h` lines you mention but i could not find the section you mentioned to comment out. I still get the same error with adding the lines you suggested :(

**Comment by khavishbhundoo** [comment]
@davama  @amichaelgrant  check https://github.com/Austinb/nginx-upload-module

**Comment by davama** [comment]
@khavishbhundoo  thank you!

That worked!

**Comment by fdintino** [comment]
Not dead anymore!

**Comment by Bhuvanamitra** [comment]
I am facing lot of trouble in compiling Nginx along with nginx-upload-module
Can someone help in figuring out correct version combination of nginx and nginx-upload-module?
